// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzzwjopalvopvgofepvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6endqb3BhbHZvcHZnb2ZlcHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzQ2NTAsImV4cCI6MjA3MDUxMDY1MH0.tU-a1FG6FOB8WdcXWcl2ZYV8eb4x8-1_mcLkcvbYtOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Fix RLS policies for tasks and related tables
export const fixRLSPolicies = async () => {
  try {
    const { data, error } = await supabase.functions.invoke('setup-rls');
    if (error) {
      console.error('Error fixing RLS policies:', error);
      throw error;
    }
    console.log('RLS policies fixed successfully:', data);
    return data;
  } catch (error) {
    console.error('Failed to fix RLS policies:', error);
    throw error;
  }
};